// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGO71JEumYaw9zQ5mLUkZc8loBFN8EA-U',
    appId: '1:881809103183:web:08536e693170dac0d58d3a',
    messagingSenderId: '881809103183',
    projectId: 'mechicetest',
    authDomain: 'mechicetest.firebaseapp.com',
    storageBucket: 'mechicetest.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYzFs85Z6OPudv1jaFsbQlv3uqbeywwvQ',
    appId: '1:881809103183:android:a06a6a8c95c885b8d58d3a',
    messagingSenderId: '881809103183',
    projectId: 'mechicetest',
    storageBucket: 'mechicetest.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDImKFbzzPaSU_c-3FtLQdzHAEw9yCMcVQ',
    appId: '1:881809103183:ios:33d28ef37accda64d58d3a',
    messagingSenderId: '881809103183',
    projectId: 'mechicetest',
    storageBucket: 'mechicetest.firebasestorage.app',
    iosBundleId: 'com.example.mechineTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDImKFbzzPaSU_c-3FtLQdzHAEw9yCMcVQ',
    appId: '1:881809103183:ios:33d28ef37accda64d58d3a',
    messagingSenderId: '881809103183',
    projectId: 'mechicetest',
    storageBucket: 'mechicetest.firebasestorage.app',
    iosBundleId: 'com.example.mechineTest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBGO71JEumYaw9zQ5mLUkZc8loBFN8EA-U',
    appId: '1:881809103183:web:dcf2853f146c5512d58d3a',
    messagingSenderId: '881809103183',
    projectId: 'mechicetest',
    authDomain: 'mechicetest.firebaseapp.com',
    storageBucket: 'mechicetest.firebasestorage.app',
  );
}
